apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: global-alert-manager-configuration
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  receivers:
    - name: slack-notifications
      slackConfigs:
        - channel: "#alerts" # your channel name that you have created
          sendResolved: true
          iconEmoji: ":bell:"
          text: "<!channel>  Alert in Environment: {{ (index .Alerts 0).Labels.env }}\nAffected Pods: {{ range .Alerts }}{{ .Labels.pod }}, {{ end }}"


  route:
    matchers:
      # name of the label to match
      - name: env
        value: staging
        matchType: =
    groupBy: ["job", "severity"]
    groupWait: 30s
    receiver: slack-notifications
    groupInterval: 1m
    repeatInterval: 1m





