apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: kube-prometheus
  name: dev-rule
  namespace: monitoring
spec:
  groups:
    - name: "dev.rules"
      rules:
        - alert: PodDown
          for: 1m
          # expr: kube_pod_status_ready{condition="true",pod=~".*"}==0
          expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
          labels:
            severity: critical
            env: staging
